image:https://img.shields.io/github/license/ursjoss/JRis.svg[LICENSE, link=https://github.com/ursjoss/scipamato/blob/master/LICENSE]
image:https://github.com/ursjoss/JRis/workflows/Check/badge.svg?branch=master[LICENSE, link=https://github.com/ursjoss/JRis]
image:https://sonarcloud.io/api/project_badges/measure?project=ursjoss_JRis&metric=alert_status[Quality Gate, link=https://sonarcloud.io/dashboard?id=ursjoss_JRis]

== JRis

JRis is a Kotlin implementation of RIS Format - currently forked from fastlucas Java implementation
available on https://github.com/fastluca/JRis[Github].
JRis has the goal to give an easy way to parse RIS format stream and to build them.

From https://en.wikipedia.org/wiki/RIS_(file_format)[Wikipiedia]:

====
RIS is a standardized tag format developed by Research Information Systems,
Incorporated (the format name refers to the company) to  enable citation programs to exchange data.
It is supported by a number of reference managers.
Many digital libraries, like IEEE Xplore, Scopus, the ACM Portal, Scopemed, ScienceDirect,
SpringerLink and Rayyan QCRI can export citations in this format.
Major reference/citation manager applications, like Zotero, Mendeley, and EndNote can export
and import citations in this format.
====