:krisVersion: 0.2.4

image:https://img.shields.io/github/license/ursjoss/KRis.svg[LICENSE, link=https://github.com/ursjoss/KRis/blob/master/LICENSE]
image:https://github.com/ursjoss/KRis/workflows/Check/badge.svg?branch=master[LICENSE, link=https://github.com/ursjoss/KRis]
image:https://sonarcloud.io/api/project_badges/measure?project=ursjoss_KRis&metric=alert_status[Quality Gate, link=https://sonarcloud.io/dashboard?id=ursjoss_KRis] image:https://sonarcloud.io/api/project_badges/measure?project=ursjoss_KRis&metric=coverage[Coverage, link=https://sonarcloud.io/dashboard?id=ursjoss_KRis]

== KRis

KRis is a Kotlin implementation of RIS Format -- forked from fastlucas Java implementation https://github.com/fastluca/JRis[JRis].
KRis has the goal to give an easy way to parse RIS format stream and to build them.

From https://en.wikipedia.org/wiki/RIS_(file_format)[Wikipiedia]:

====
RIS is a standardized tag format developed by Research Information Systems,
Incorporated (the format name refers to the company) to  enable citation programs to exchange data.
It is supported by a number of reference managers.
Many digital libraries, like IEEE Xplore, Scopus, the ACM Portal, Scopemed, ScienceDirect,
SpringerLink and Rayyan QCRI can export citations in this format.
Major reference/citation manager applications, like Zotero, Mendeley, and EndNote can export
and import citations in this format.
====


More documentation can be found in the https://ursjoss.github.io/KRis/[Guide]
and https://ursjoss.github.io/KRis/kapi/-k-ris/index.html[KDoc].

== Setup

.Gradle depending on KRisc-core and - optionally - KRis-io
[code,kotlin]
----
repositories {
    jcenter()
}

dependencies {
    implementation("ch.difty.kris:kris-core:{krisVersion}")
    implementation("ch.difty.kris:kris-io:{krisVersion}")
}
----

.Maven depenency on KRis-core and - optionally - KRis-io
[code,xml]
----
<dependency>
	<groupId>ch.difty.kris</groupId>
	<artifactId>kris-io</artifactId>
	<version>{krisVersion}</version>
	<type>pom</type>
</dependency>
<dependency>
	<groupId>ch.difty.kris</groupId>
	<artifactId>kris-core</artifactId>
	<version>{krisVersion}</version>
	<type>pom</type>
</dependency>
----
