detekt-hint:
  UseCompositionInsteadOfInheritance:
    active: true
    yourUniquePackageName: "ch.difty.kris"
  LackOfCohesionMethods:
    active: true
    threshold: "0.8"
  InterfaceSegregationPrinciple:
      active: true
  OpenClosedPrinciple:
      active: true
